version: '3.1'

services:

  dev-db:
    image: mysql:latest
    container_name: dev-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1azerty.
    ports:
      - 3306:3306
    volumes:
      - dev-db-data:/var/lib/mysql


volumes:
  dev-db-data:
